version: '3'

services:
  local:
    container_name: "babylon-local"
    image: "ghcr.io/qj0r9j0vc2/babylon:v1.0.0-rc.3-logging"
    command:
      - bash
      - -c
      - "babylond start --home=/home/babylon/babylond/ 2>&1 | tee /home/babylon/babylond/container.log"
    volumes:
      - ./babylon/:/home/babylon/
    ports:
      - "26657:26657"
